image: docker:${DOCKER_VERSION}

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

services:
  - docker:${DOCKER_VERSION}-dind

stages:
  - build
  - upload

build:
  stage: build
  script:
   - rm image-files/dokuwiki/install.php
   - docker build -t dokuwiki:latest image-files/
   - docker save dokuwiki | gzip > dokuwiki.tgz
  artifacts:
    paths:
      - dokuwiki.tgz

upload:
  stage: upload
  when: manual
  script:
    - zcat dokuwiki.tgz | docker load
    - docker tag dokuwiki:latest push.${REGISTRY_URL}/dokuwiki
    - docker login https://${REGISTRY_URL} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker push push.{REGISTRY_URL}/dokuwiki
