#!/bin/sh
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

C1=`echo ${DOCKER_TAG} | cut -d "-" -f 1`
C2=`echo ${DOCKER_TAG} | cut -d "-" -f 2`
C3=`echo ${DOCKER_TAG} | cut -d "-" -f 3`

echo "$C1 $C2 $C3"

if [ "${C1}" == "latest" ]; then
    FLAG_VERSION="--build-arg VERSION=latest"
fi

if [ "${C1}" == "rc" ]; then
    FLAG_VERSION="--build-arg VERSION=release-candidate"
fi

if [ "${C2}" == "installer" ]; then
    FLAG_INSTALLER="--build-arg INSTALLER=true"
fi

if [ "${C2}" == "ldap" ]; then
    FLAG_LDAP="--build-arg LDAP=true"
fi

if [ "${C2}" != "${C3}" ] && [ "${C3}" == "installer" ]; then
    FLAG_INSTALLER="--build-arg INSTALLER=true"
fi

if [ "${C2}" != "${C3}" ] && [ "${C3}" == "ldap" ]; then
    FLAG_LDAP="--build-arg LDAP=true"
fi

docker build -t ${IMAGE_NAME} \
    ${FLAG_VERSION} ${FLAG_INSTALLER} ${FLAG_LDAP} image-files/
