#!/bin/sh
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

C1=`echo ${DOCKER_TAG} | cut -d "-" -f 1`
C2=`echo ${DOCKER_TAG} | cut -d "-" -f 2`
C3=`echo ${DOCKER_TAG} | cut -d "-" -f 3`


IMD="image-files/"

[[ $C1 == "latest" ]] && FLAG_VERSION="--build-arg VERSION=latest"
[[ $C1 == "rc" ]] && FLAG_VERSION="--build-arg VERSION=release-candidate"

[[ $C2 == "installer" ]] && FLAG_INSTALLER="--build-arg INSTALLER=true"
[[ $C2 == "ldap" ]] && FLAG_LDAP="--build-arg LDAP=true"

[[ $C2 != $C3 ]] && [[ $C3 == "installer" ]] && FLAG_INSTALLER="--build-arg INSTALLER=true"
[[ $C2 != $C3 ]] && [[ $C3 == "ldap" ]] && FLAG_LDAP="--build-arg LDAP=true"

docker build -t ${IMAGE_NAME}:${DOCKER_TAG} ${FLAG_VERSION} ${FLAG_INSTALLER} ${FLAG_LDAP} ${IMD}
