#!/bin/sh
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

#

C1=`echo ${DOCKER_TAG} | cut -d "-" -f 1`
C2=`echo ${DOCKER_TAG} | cut -s -d "-" -f 2`
C3=`echo ${DOCKER_TAG} | cut -s -d "-" -f 3`




[ ! -z "${C1}" ] && [ "${C1}" == "latest" ] && FLAG_VERSION="--build-arg VERSION=latest"

[ ! -z "${C1}" ] && [ "${C1}" == "rc" ] && FLAG_VERSION="--build-arg VERSION=release-candidate"

[ ! -z "${C2}" ] && [ "${C2}" == "installer" ] &&  FLAG_INSTALLER="--build-arg INSTALLER=true"

[ ! -z "${C2}" ] && [ "${C2}" == "ldap" ] && FLAG_LDAP="--build-arg LDAP=true"

[ ! -z "${C3}" ] && [ "${C2}" != "${C3}" ] && [ "${C3}" == "installer" ] && FLAG_INSTALLER="--build-arg INSTALLER=true"

[ ! -z "${C3}" ] && [ "${C2}" != "${C3}" ] && [ "${C3}" == "ldap" ] && FLAG_LDAP="--build-arg LDAP=true"

docker build -t dokuwiki:${DOCKER_TAG} ${FLAG_VERSION} ${FLAG_INSTALLER} ${FLAG_LDAP} .
